config/routes.rb
Rails.application.routes.draw do

  resources :pokemon

  root 'pokemon#index'

end

app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
    validates :name, presence: true, length: {minimum: 3}
    validates :types, presence: true
    mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pokemon_controller.rb
class PokemonController < ApplicationController
  @@types = ["bug", "dragon", "ice", "fighting", "fire", "flying", "grass", "ghost", "ground", "electric", "poison", "psychic", "rock", "water"]

  def index
      @pokemon_list = Pokemon.all
  end

  def edit
      @types = @@types
      @pokemon = Pokemon.find(params[:id])
      @types_on = { }
      for type in @pokemon.types.split(", ")
          @types_on[type.downcase()] = 1
      end
      @weaknesses_on = { }
      for weak in @pokemon.weaknesses.split(", ")
          @weaknesses_on[weak.downcase()] = 1
      end
  end

  def new
      @types = @@types
      if !(@pokemon)
          @pokemon = Pokemon.new
      end
  end

  def show
      @pokemon = Pokemon.find(params[:id])
  end

  def create
     new_pokemon = generate_pokemon(params[:pokemon])

     @pokemon = Pokemon.new(new_pokemon)
     if @pokemon.save
         redirect_to @pokemon
     else
         render 'new'
     end
  end

  def update
      @pokemon = Pokemon.find(params[:id])
      pokemon_params = generate_pokemon(params[:pokemon])

      if @pokemon.update(pokemon_params)
          redirect_to @pokemon
      else
          render 'edit'
      end
  end

  def destroy
      @pokemon = Pokemon.find(params[:id])
      if @pokemon.destroy
          redirect_to 'pokemon#index'
      end
  end

  private
  def generate_pokemon(p)
      new_pokemon = { }
      ## Fetch simple string params
      new_pokemon["name"] = p["name"]
      new_pokemon["description"] = p["description"]
      ## Generate abilities list string
      new_pokemon["abilities"] = p["abilities"].split("\r\n").join(", ")
      ## Generate types list string
      new_pokemon["types"] = ""
      isFirst = true
      @types = @@types
      for x in @types
          if (p["type_" + x] == "on")
              if (!isFirst)
                  new_pokemon["types"] += ", "
              end
              new_pokemon["types"] += x.capitalize()
              isFirst = false
          end
      end

      if (new_pokemon["types"] == "")
          new_pokemon["types"] = "Normal"
      end

      ## Generate weaknesses list string
      new_pokemon["weaknesses"] = ""
      isFirst = true
      for x in @types
          if (p["weak_" + x] == "on")
              if (!isFirst)
                  new_pokemon["weaknesses"] += ", "
              end
              new_pokemon["weaknesses"] += x.capitalize()
              isFirst = false
          end
      end
      ## Add image
      new_pokemon["image"] = p["image"]

      return new_pokemon
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokedex</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pokemon/edit.html.erb
<%= link_to 'Back', pokemon_index_path %>

<h1>Edit Pokemon</h1>

<%= form_for @pokemon, url: pokemon_path(@pokemon), method: :patch do |form| %>

    <% if @pokemon.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pokemon.errors.count, "error") %> prevented this Pokemon from being saved.
      </h2>
      <ul>
        <% @pokemon.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <fieldset>
        <%= form.label :name %>
        <%= form.text_field :name %>

        <%= form.label :description %>
        <%= form.text_area :description %>

        <%= image_tag @pokemon.image_url.to_s, class:'avatar' %>
        <%= form.label :image %>
        <%= form.file_field :image %>
    </fieldset>

    <fieldset>
        <label for="pokemon[abilities]">Abilities (one per line)</label>
        <%= form.text_area :abilities %>

        <label>Type(s)</label>
        <fieldset class="block-set">
            <% for type in @types %>
                <p>
                    <% if @types_on[type]%>
                        <input type="checkbox" checked name="pokemon[<%= 'type_' + type %>]" id="pokemon_<%= 'type_' + type %>" /><%= type.capitalize() %>
                    <% else %>
                        <input type="checkbox" name="pokemon[<%= 'type_' + type %>]" id="pokemon_<%= 'type_' + type %>" /><%= type.capitalize() %>
                    <% end %>
                </p>
            <% end %>
        </fieldset>

        <label>Weakness(es)</label>
        <fieldset class="block-set">
            <% for weakness in @types %>
            <p>
                <% if @weaknesses_on[weakness]%>
                    <input type="checkbox" checked name="pokemon[<%= 'weak_' + weakness %>]" id="pokemon_<%= 'weak_' + weakness %>" /><%= weakness.capitalize() %>
                <% else %>
                    <input type="checkbox" name="pokemon[<%= 'weak_' + weakness %>]" id="pokemon_<%= 'weak_' + weakness %>" /><%= weakness.capitalize() %>
                <% end %>
            </p>
            <% end %>
        </fieldset>
    </fieldset>

    <%= form.submit %>

<% end %>

app/views/pokemon/index.html.erb
<h1>Pokemon</h1>

<%= link_to 'New Pokemon', '/pokemon/new' %>

<ul class="roster">
    <% for pokemon in @pokemon_list %>
    <li>
        <section>
            <%= image_tag pokemon.image_url.to_s, class:'avatar' %>
        </section>
        <section>
            <h4><%= pokemon.name %></h4>
            <p>(<%= pokemon.types %>)</p>
            <p><%= pokemon.description %></p>
            <p>
                <%= link_to 'Show details', '/pokemon/' + String(pokemon.id) %>
                &nbsp;
                <%= link_to 'Edit', '/pokemon/' + String(pokemon.id) + '/edit' %>
                &nbsp;
                <%= link_to 'Delete', '/pokemon/' + String(pokemon.id),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
            </p>
        </section>
    </li>
    <% end %>
</ul>

app/views/pokemon/new.html.erb
<%= link_to 'Back', pokemon_index_path %>

<h1>New Pokemon</h1>

<%= form_for @pokemon, url: '/pokemon' do |form| %>

    <!--Error messages-->
    <% if @pokemon.errors.any? %>
    <div class="msg-err">
      <h2>
        <%= pluralize(@pokemon.errors.count, "error") %> prevented this Pokemon from being saved:
      </h2>
      <ul>
        <% @pokemon.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <fieldset>
        <%= form.label :name %>
        <%= form.text_field :name %>

        <%= form.label :description %>
        <%= form.text_area :description %>

        <%= form.label :image %>
        <%= form.file_field :image %>
    </fieldset>

    <fieldset>
        <label for="pokemon[abilities]">Abilities (one per line)</label>
        <%= form.text_area :abilities %>

        <label>Type(s)</label>
        <fieldset class="block-set">
            <% for type in @types %>
                <p><input type="checkbox" name="pokemon[<%= 'type_' + type %>]" id="pokemon_<%= 'type_' + type %>" /><%= type.capitalize() %></p>
            <% end %>
        </fieldset>

        <label>Weakness(es)</label>
        <fieldset class="block-set">
            <% for weakness in @types %>
            <p><input type="checkbox" name="pokemon[<%= 'weak_' + weakness %>]" /><%= weakness.capitalize() %></p>
            <% end %>
        </fieldset>
    </fieldset>

    <%= form.submit %>

<% end %>

app/views/pokemon/show.html.erb
<%= link_to 'Back', pokemon_index_path %>

<h1><%= @pokemon.name %></h1>
<%= image_tag @pokemon.image_url.to_s, class:'avatar' %>

<h4>Description</h4>
<p>
    <%= @pokemon.description %>
</p>

<h4>Abilities</h4>
<p>
    <%= @pokemon.abilities %>
</p>

<h4>Types</h4>
<p>
    <%= @pokemon.types %>
</p>

<h4>Weaknesses</h4>
<p>
    <%= @pokemon.weaknesses %>
</p>